### ISSUE TITLE
[legacy][jun19p2] xrootd fails to build on GCC 9; partially fixed upstream

### ISSUE THREAD

**Issue by ttrubep1** [FairRootGroup/FairSoft#375]
Yesterday, I tried to compile FairSoft in order to install PandaRoot on the desktop system at my institute ([Ruhr-Universität Bochum, Institut für Experimentalphysik I](https://www.ep1.ruhr-uni-bochum.de/en/)). Our desktop machines run CentOS 8, GCC 9.2.0, and Python 3.6.8.

I used FairSoft version `jun19p2` as it is currently recommended by the PANDA computing coordinator @TobiasStockmanns for analysis work.

There were several obstacles in compiling FairSoft in my environment, one of them concerns xrootd.

On the one hand, there was an incorrect return type in one copy assignment operator (the `&` was missing), this has already been addressed upstream: https://github.com/xrootd/xrootd/commit/fa79ae62bb6e01cb3c0c0823c3111ffd31a8c0db#diff-42f9c7cc58eefe74635cf7e5275711cd8ff38fc9cae771648de3659ad87c062b

On the other hand, there are several classes that explicitly define a copy assignment operator, but do not mention the copy constructor at all, nevertheless use it in other parts of the code, so that the copy constructor is implicitly generated by the compiler. Recent versions of GCC produce a warning there as this programming practice is [error-prone and deprecated](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c21-if-you-define-or-delete-any-copy-move-or-destructor-function-define-or-delete-them-all).

Unfortunately, xrootd [compiles using the `-Werror` flag by default](https://github.com/xrootd/xrootd/blob/ef2c83b0e346aeb08b1f54db564bf13f4cf5d81d/docs/ReleaseNotes.txt#L992), so that the warnings mentioned above terminate the compilation sequence.

As a workaround, I removed the `-Werror` flag in line 29 of `/tools/root/build_for_fair/XROOTD-prefix/src/XROOTD/cmake/XRootDOSDefs.cmake`.

As this issue breaks the compilation of FairSoft on any modern version of GCC, I suggest checking if moving to a more recent version of xrootd can fix this, or edit `XRootDOSDefs.cmake` from the installation script to disable `-Werror`.

**Comment by dennisklein** [comment]
Thank you for the detailed report.

> I suggest checking if moving to a more recent version of xrootd can fix this,

Changing versions in the `jun19` FairSoft release is less desirable since we did not have a clear definition if the version was meant to be pinned or if the package was just included for the sake of having "some" xrootd at all. So, I would like to not break anyone who is expecting `jun19` to include this specific xrootd version.

However, in future releases of FairSoft we are working on making it much clearer which package versions are meant to be pinned down because of physics-sensitive reasons and which packages are just included but would work with a range of versions (e.g. compare the [`jun19`](https://github.com/FairRootGroup/FairSoft/blob/dev/env/jun19/sim/spack.yaml) and [`nov20`](https://github.com/FairRootGroup/FairSoft/blob/dev/env/nov20/sim/spack.yaml) spack environments - the exactly pinned package version are already significantly reduced and there is probably more room to improve further). Once we fully switch to the spack package manager (we started a [beta phase with the `nov20` release](https://github.com/FairRootGroup/FairSoft/blob/dev/docs/README.md)) it will also be more straightforward for the user to slightly deviate from any given release in order to support newer platforms or include custom extra dependencies/flags.

> or edit XRootDOSDefs.cmake from the installation script to disable -Werror.

This sounds like a more desirable fix for the `jun19` release. I will test and include it with a new patch release `jun19p3` within the next days.

**Comment by ttrubep1** [comment]
@dennisklein, thanks for you quick reply.

But maybe you wait a bit with the release of `jun19p3`, as I stumbled upon some more problems when building FairSoft, I just need to the find the time to write it up as a proper bug report.

**Comment by dennisklein** [comment]
@ttrubep1 Do you still need the XRootD patch for `jun19`?

**Comment by ttrubep1** [comment]
@dennisklein, a few days ago the new PandaRoot version 12.0.0 was released which is now based on the FairSoft release `nov20`, so the answer is most probably no.

But I did not have time to install the new PandaRoot version yet because the project that needs PandaRoot has been put on hiatus as other things are more important right now at my institute.

But maybe next week I will find time to update my PandaRoot installation...

**Comment by dennisklein** [comment]
Closing, because it is likely resolved. Re-open, if you still need the XRootD patch for `jun19`!
