### ISSUE TITLE
Compiling FairSoft with PyTorch C++ API

### ISSUE THREAD

**Issue by a-akram** [FairRootGroup/FairSoft#431]
Hi All, 

I am wondering what will be an appropriate way to install/build C++ API of PyTorch with FairSoft? I'm writing a FairTask which need PyTorch library for my ML+PandaRoot project. It has become a bottleneck.

I would appreciate if someone can give some guide to compile FairSoft with PyTorch. Or if there is better way to integrate both.

**Comment by dennisklein** [comment]
I just see that there is already a py-torch package in upstream Spack: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-torch/package.py

Please test if this works for your use case and tell us the exact package spec you will need (A [spec](https://spack.readthedocs.io/en/latest/basic_usage.html#specs-dependencies) is a Spack term). This `py-torch` package is non-trivial and has a lot of [variants](https://github.com/spack/spack/blob/9853fd50e2dc6253a2c80b38fc3bad8f226ce94e/var/spack/repos/builtin/packages/py-torch/package.py#L54-L76) - which is why you need to be specific what you need, so we can port it accordingly to legacy FairSoft!

**Comment by ChristianTackeGSI** [comment]
Or alternatively, can you tell us you manual procedure for installing libtorch / pytorch after FairSoft?

That way we can possibly look at the spack `package.py` recipes to deduce the proper options for it.
And we likely can create the "legacy" cmake code to install it as well.

**Comment by a-akram** [comment]
@dennisklein @ChristianTackeGSI May I ask if something is happening in this regard?

The PyTorch version I mentioned earlier is **1.8.2** which is termed as the **LTS** version on the official website (it is already in the Spack package list, in the future one can go from one LTS to another). Building this package optionally is well thought as not all PandaRoot users need it. Right now, we are using the **legacy** build process as it is simple, stable and easy to understand.

Meanwhile, if you can provide instructions for [legacy.cmake](https://github.com/FairRootGroup/FairSoft/blob/master/cmake/legacy.cmake) then I would like to build a singularity container out of it.

**Comment by dennisklein** [comment]
Just for reference my post in the FairSoft mattermost channel on 25th October @6:37 PM:
```
I had a look at the py-torch package and my conclusion is that it is not worth the effort adding it to the legacy FairSoft, because of the size of its dependency tree. So, unless you want to invest this time, I doubt anyone from us will find the time. Also, I have not yet understood how they create their libtorch binary package. The website appears to document binary distribution only ...
```

**Comment by dennisklein** [comment]
for reference: https://github.com/spack/spack/issues/28679

Next steps:
* [ ] Add a py-torch spec to the {`dev` or new ML?} environments
* [ ] Document how to opt-in for cuda support

**Comment by fuhlig1** [comment]
@a-akram,

with the FairSoft release nov22 we ship the ONNXRuntime as additional package. The package allows to load and use models for inference produced by several ML projects. There is for sure a way to export PyTorch models to the onnx format which then can be used with PandaRoot.

I will now close this issue since we don't intent to add any ML framework to FairSoft in favour of the ONNXRuntime package.
