### ISSUE TITLE
Fairsoft and FR on lxplus

### ISSUE THREAD

**Issue by EugeniaSpedicato** [FairRootGroup/FairSoft#435]
Hi everyone,

i've a question (which I've partially asked yet) about installing fairsoft (and FairRoot) on the cern lxplus machine. I've seen that the ship experiment was able to do that. Is it possible to do it without root privileges? Is there a cvmfs repository or I can do it just on my personal computer?

Thank you

**Comment by dennisklein** [comment]
Dear @EugeniaSpedicato, after discussing your request in our group meeting, I can inform you, that at this point in time, we are not offering binary pre-compilations suitable for lxplus maintained by us. In general, we are currently working on providing pre-compiled binaries in some form in the future, because this is indeed a popular request, but again - at this point in time - I cannot foresee, if those will be suitable for lxplus - there are currently no plans to target lxplus specifically.

> I've seen that the ship experiment was able to do that.

Unfortunately I am not experienced with lxplus or how ship accomplished such installations. Probably best to ask them directly.
