### ISSUE TITLE
optical photon propabation bug in geant4 10.7.1

### ISSUE THREAD

**Issue by rdom** [FairRootGroup/FairSoft#447]
The apr21 version of FairSoft includes geant4 version which has bug with optical photon propagation (https://bugzilla-geant4.kek.jp/show_bug.cgi?id=2438). This affects the propagation of Cherenkov photons inside DIRC detector using PandaRoot. Would be good to create a patch or bump the geant4 version to 10.11 where this bug is fixed.

**Comment by dennisklein** [comment]
It is likely we will include Geant4 `11.0.0` only in the next FairSoft release (likely `feb22` or `mar22`) by policy, because it is a major version bump. However, the new release will also bump the ROOT version and others. If you need an urgent fix for the `apr21_patches` branch, may I ask you to prepare a patch file against Geant4 `10.7.1` (only if you feel confident in picking the right diff and can verify it is working)? The problem for me is, Geant4 does not publish its commit history (or at least I have not found it yet)...

**Comment by rdom** [comment]
Currently we are using local fix, so it is not urgent.  In a longer term we will wait for a new release of FairSoft with upgraded geant4.
