### ISSUE TITLE
MACOS VENTURA 13.4 Problem with "root-build-RelWithDebInfo.cmake" 

### ISSUE THREAD

**Issue by LeoFoorm** [FairRootGroup/FairSoft#538]
I am installing FairSoft by following the instructions of legacy. I think I did every step correctly. At the moment of **cmake --build <path-to-build> [-j<ncpus>]** (my path is _cmake --build FairSoft-build_) it showed this

CMake Error at /Users/leonardofernandezluna/Documents/FairSoft-build/Stamp/root/root-build-RelWithDebInfo.cmake:37 (message):
  Command failed: 2

   '/Library/Developer/CommandLineTools/usr/bin/make'

  See also

    '/Users/leonardofernandezluna/Documents/FairSoft-build/Log/root-build.log'
![Uploading Captura de pantalla 2024-05-07 a la(s) 10.58.49.png…]()

**Comment by dennisklein** [comment]
Hm, can you pls upload the log file that is mentioned under 'see also'? I see you attached an image, but something went wrong, one cannot acces it. Also, pls don't attach screenshots of shell text, just copy the text here as text.

**Comment by LeoFoorm** [comment]
sorry for the screenshot. Here it is the log file:

[root-build.log](https://github.com/FairRootGroup/FairSoft/files/15241015/root-build.log)

**Comment by dennisklein** [comment]
```
[ 97%] Linking CXX shared library ../../lib/libROOTEve.so
Undefined symbols for architecture x86_64:
  "ROOT::Experimental::REveElement::WriteCoreJson(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>&, int)", referenced from:
      vtable for ROOT::Experimental::REveDataColumn in G__ROOTEve.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [lib/libROOTEve.6.30.02.so] Error 1
make[4]: *** [graf3d/eve7/CMakeFiles/ROOTEve.dir/all] Error 2
```

I have not seen this error before. I will have a look at it tomorrow.

**Comment by LeoFoorm** [comment]
thank you vm. I will be in touch.

**Comment by dennisklein** [comment]
I am not sure what is going wrong here tbh, one thing you could try is to use the json library from brew, which is newer than the vendored one and may have fixed the issue already:

1. [`brew install nlohmann-json`](https://formulae.brew.sh/formula/nlohmann-json)
2. [Clone](https://github.com/FairRootGroup/FairSoft/blob/jan24_patches/legacy/README.md#2-clone-the-git-repo) the FairSoft [branch `jan24_patches`](https://github.com/FairRootGroup/FairSoft/tree/jan24_patches) instead of [tag `jan24`](https://github.com/FairRootGroup/FairSoft/tree/jan24)
3. Modify the file [`cmake/legacy.cmake`](https://github.com/FairRootGroup/FairSoft/blob/jan24_patches/cmake/legacy.cmake) as follows
```cmake
--- a/cmake/legacy.cmake
+++ b/cmake/legacy.cmake
@@ -376,7 +376,7 @@ ExternalProject_Add(root
   ${CMAKE_DEFAULT_ARGS} CMAKE_ARGS
     "-Daqua=ON"
     "-Dasimage=ON"
-    "-Dbuiltin_nlohmannjson=ON"
+    "-Dbuiltin_nlohmannjson=OFF"
     "-Dcintex=OFF"
     "-Ddavix=OFF"
     "-Dfftw3=ON"
```
4. Continue to [configure and build as usual](https://github.com/FairRootGroup/FairSoft/blob/jan24_patches/legacy/README.md#3-cmake-configure-step)

**Comment by LeoFoorm** [comment]
it worked

**Comment by LeoFoorm** [comment]
thank you very much
