### ISSUE TITLE
Disable ROOT Fortran support?

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairSoft#542]
Hi,

I'm trying to build FairSoft in a Debian buster system (lxir136). I can't get a successful compilation unless I disable ROOT support to Fortran, which is the default from ROOT.

Is there any reason that we need this Fortran support from ROOT?

PS: Is it also possible we enable MT support of Geant4?

**Comment by dennisklein** [comment]
What error do you get with fortran enabled? I will clarify with our group why and for what this is needed and report back.

> Is it also possible we enable MT support of Geant4?

Yes, we have configuration option for this ([`-DGEANT4MT=ON`](https://github.com/FairRootGroup/FairSoft/blob/1e700776a7e26a3d5427ee3f6308b82d39a32418/FairSoftConfig.cmake#L38). Check the comment column in the table that is printed during CMake configuration phase.

**Comment by YanzhaoW** [comment]
Hi,

The error is related to compilation of `h2root`, which needs a very old Fortran compiler (g77).

I don't have the error message currently at hand. I may post the error messages here in a few days.

**Comment by fuhlig1** [comment]
Hi @YanzhaoW,

FairSoft builds without problems for Debian Buster. We have several FairSoft versions installed at /cvmfs/fairsoft.gsi.de/debian10/fairsoft/ including the latest version jan24p1. Instead of g77 which is really outdated for the compilation of h2root gfortran is used. I crosschecked  and the h2root binary is installed for all our FairSoft installations on CVMFS.
