### ISSUE TITLE
jan24 compilation error with Numpy 2

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairSoft#550]
see https://github.com/boostorg/python/issues/431

This was reported via email to me by a macOS user who seems to have the latest Numpy via Homebrew.

**Comment by fuhlig1** [comment]
Hi Dennis,

I had the same problem and the reported solution works also with our FairSoft. We should add the patch from the GitHub discussion since it also catches the case when using older lumpy versions.

Ciao

Florian

On 15. Aug 2024, at 12:23, Dennis Klein ***@***.***> wrote:



see boostorg/python#431<https://github.com/boostorg/python/issues/431>

This was reported via email to me by a macOS user who seems to have the latest Numpy via Homebrew.
